H-chauvet/RISU

Application/mobile/app_code/lib/pages/login/login_state.dart
Application/mobile/app_code/lib/pages/profile/informations/informations_functional.dart
Application/mobile/app_code/lib/pages/profile/informations/informations_page.dart
Application/mobile/app_code/lib/pages/profile/informations/informations_state.dart
Application/mobile/app_code/lib/pages/profile/profile_state.dart
Application/mobile/app_code/lib/router.dart
Application/server/server.js

ajout de la page de modification des informations du profile (mobile)

[ADD] update informations profile

---

Configurateur/front/lib/components/google.dart
Configurateur/front/lib/screens/login/login.dart
Configurateur/front/lib/screens/password-recuperation/password-recuperation.dart
Configurateur/front/lib/screens/password-recuperation/password_change.dart

added for connexion (success/fail)
added for google connexion (success/fail)
added for pasword change (success/fail)
added for password recovery (success/fail)
tests will come later

[WEB] graphical signal for back response

---

Application/mobile/app_code/lib/pages/home/home_state.dart

opinion list + opinion filter by note + opinion creation + tests front-end and back-end
merge to dev

[FIX] add profile in navbar

---

Application/mobile/app_code/lib/pages/profile/profile_state.dart
Application/mobile/app_code/pubspec.yaml

[FIX] Too long name in profile

---

Application/mobile/app_code/lib/pages/article/article.dart
Application/mobile/app_code/lib/pages/opinion/opinion_page.dart
Application/mobile/app_code/lib/pages/opinion/opinion_state.dart
Application/mobile/app_code/lib/pages/settings/settings_state.dart
Application/mobile/app_code/test/opinion_test.dart
Application/server/prisma/schema.prisma
Application/server/server.js
Application/server/tests/opinion.test.js

added access to opinion page in parameters and opinion page, tests front + back

[ADD] fix opinion page + tests front and back

---

Application/mobile/app_code/lib/components/parameter.dart

Could not click on empty space before

[FIX] click behavior

---

Application/mobile/app_code/lib/pages/settings/settings_state.dart
Application/mobile/app_code/test/setting_test.dart

Feature/282 -Delete account implemented and tested

---

Application/mobile/app_code/lib/pages/rent/confirm/confirm_rent_page.dart
Application/mobile/app_code/lib/pages/rent/confirm/confirm_rent_state.dart
Application/mobile/app_code/lib/pages/rent/rent_state.dart
Application/mobile/app_code/test/confirm_rent_test.dart

Feature 278 - Confirm page for rent

---

Application/mobile/app_code/lib/components/alert_dialog.dart
Application/mobile/app_code/lib/globals.dart
Application/mobile/app_code/lib/pages/article/details_state.dart
Application/mobile/app_code/lib/pages/article/list_state.dart
Application/mobile/app_code/lib/pages/contact/contact_state.dart
Application/mobile/app_code/lib/pages/container/container_state.dart
Application/mobile/app_code/lib/pages/container/details_state.dart
Application/mobile/app_code/lib/pages/home/home_state.dart
Application/mobile/app_code/lib/pages/login/login_state.dart
Application/mobile/app_code/lib/pages/map/map_state.dart
Application/mobile/app_code/lib/pages/opinion/opinion_state.dart
Application/mobile/app_code/lib/pages/profile/informations/informations_state.dart
Application/mobile/app_code/lib/pages/rent/rent_state.dart
Application/mobile/app_code/lib/pages/settings/settings_pages/notifications/notifications_state.dart
Application/mobile/app_code/lib/pages/settings/settings_state.dart
Application/mobile/app_code/lib/pages/signup/signup_state.dart
Application/mobile/app_code/lib/utils/validators.dart
Application/mobile/app_code/test/profile_info_test.dart
Application/server/tests/apiContainer.test.js

[Screen_recording_20240126_090811.webm](https://github.com/H-chauvet/RISU/assets/72006230/8c0eaeed-11fd-4cd7-b7a2-bf27a8e37888)

User information management

---

Application/mobile/app_code/lib/components/appbar.dart
Application/mobile/app_code/lib/pages/article/details_state.dart
Application/mobile/app_code/lib/pages/article/list_state.dart
Application/mobile/app_code/lib/pages/contact/contact_state.dart
Application/mobile/app_code/lib/pages/container/details_state.dart
Application/mobile/app_code/lib/pages/home/home_state.dart
Application/mobile/app_code/lib/pages/login/login_state.dart
Application/mobile/app_code/lib/pages/opinion/opinion_state.dart
Application/mobile/app_code/lib/pages/profile/informations/informations_state.dart
Application/mobile/app_code/lib/pages/rent/confirm/confirm_rent_state.dart
Application/mobile/app_code/lib/pages/rent/rent_state.dart
Application/mobile/app_code/lib/pages/rent/rental_state.dart
Application/mobile/app_code/lib/pages/rent/return_state.dart
Application/mobile/app_code/lib/pages/settings/settings_pages/notifications/notifications_state.dart
Application/mobile/app_code/lib/pages/settings/settings_state.dart
Application/mobile/app_code/lib/pages/signup/signup_state.dart
Application/mobile/app_code/test/appbar_test.dart

The burger menu icon was useless
It is automatically displayed by flutter with the drawers

Hotfix - Burger Menu

---

Application/mobile/app_code/test/container_details_test.dart
Application/mobile/app_code/test/globals.dart
Application/mobile/app_code/test/opinion_test.dart
Application/mobile/app_code/test/profile_info_test.dart
Application/mobile/app_code/test/rentals_test.dart

Need to wait for the loader in the test otherwise, no widget will be found
Can impact the coverage

Hotfix - Tests improvements

---

Application/mobile/app_code/android/build.gradle
Application/mobile/app_code/lib/components/appbar.dart
Application/mobile/app_code/lib/components/parameter.dart
Application/mobile/app_code/lib/pages/article/details_state.dart
Application/mobile/app_code/lib/pages/article/list_state.dart
Application/mobile/app_code/lib/pages/contact/contact_state.dart
Application/mobile/app_code/lib/pages/container/container_state.dart
Application/mobile/app_code/lib/pages/container/details_state.dart
Application/mobile/app_code/lib/pages/home/home_state.dart
Application/mobile/app_code/lib/pages/login/login_state.dart
Application/mobile/app_code/lib/pages/opinion/opinion_state.dart
Application/mobile/app_code/lib/pages/profile/informations/informations_state.dart
Application/mobile/app_code/lib/pages/profile/profile_state.dart
Application/mobile/app_code/lib/pages/rent/rent_state.dart
Application/mobile/app_code/lib/pages/rent/rental_state.dart
Application/mobile/app_code/lib/pages/rent/return_state.dart
Application/mobile/app_code/lib/pages/settings/settings_pages/notifications/notifications_state.dart
Application/mobile/app_code/lib/pages/settings/settings_state.dart
Application/mobile/app_code/lib/pages/signup/signup_state.dart
Application/mobile/app_code/lib/utils/user_data.dart
Application/mobile/app_code/pubspec.lock
Application/mobile/app_code/run
Application/mobile/app_code/test/appbar_test.dart

No UI to show
UT = 71.2%
Close #214

Mobile bugs

---

Application/mobile/app_code/lib/pages/container/container_list.dart

modification du prix si il est null par prix non défini
close #219

Liste des conteneurs

---

Application/mobile/app_code/lib/components/burger_drawer.dart
Application/mobile/app_code/lib/pages/login/login_page.dart
Application/mobile/app_code/lib/pages/login/login_state.dart
Application/mobile/app_code/lib/utils/check_signin.dart
Application/mobile/app_code/test/burger_drawer_test.dart
Application/server/server.js

https://github.com/H-chauvet/RISU/assets/72006230/f9d67886-39ed-4a83-bcc5-034dfa1b3937
Close #199

Keep path of the user when asked to log in

---

Application/mobile/app_code/test/theme_test.dart

add space between tests + use of initPage function

[ADD] initPage + space between tests

---

Server/routes/Mobile/containers.js
Server/tests/mobile/apiContainer.test.js

remove connected user check on container-details on mobile route

[FIX] remove check on mobile container

---

Configurateur/front/lib/app_routes.dart
Configurateur/front/lib/components/dialog/container_dialog.dart
Configurateur/front/lib/components/dialog/delete_container_dialog.dart
Configurateur/front/lib/components/recap_panel.dart
Configurateur/front/lib/screens/container-creation/container_creation.dart
Configurateur/front/lib/screens/container-creation/design_screen.dart
Configurateur/front/lib/styles/themes.dart
Configurateur/front/test/components/dialog/container_dialog_test.dart
Configurateur/front/test/components/recap_panel_test.dart
Configurateur/front/test/container-creation/container_creation_test.dart
Configurateur/front/test/container-creation/design_screen_test.dart

New Interface for the container creation screen.

242 configuration screen

---

Application/mobile/app_code/lib/components/burger_drawer.dart
Application/mobile/app_code/lib/globals.dart
Application/mobile/app_code/lib/pages/article/details_state.dart
Application/mobile/app_code/lib/pages/article/list_state.dart
Application/mobile/app_code/lib/pages/contact/contact_state.dart
Application/mobile/app_code/lib/pages/container/container_state.dart
Application/mobile/app_code/lib/pages/container/details_state.dart
Application/mobile/app_code/lib/pages/login/login_state.dart
Application/mobile/app_code/lib/pages/opinion/opinion_state.dart
Application/mobile/app_code/lib/pages/profile/informations/informations_state.dart
Application/mobile/app_code/lib/pages/rent/rent_state.dart
Application/mobile/app_code/lib/pages/rent/rental_state.dart
Application/mobile/app_code/lib/pages/rent/return_state.dart
Application/mobile/app_code/lib/pages/settings/settings_pages/notifications/notifications_state.dart
Application/mobile/app_code/lib/pages/settings/settings_state.dart
Application/mobile/app_code/lib/pages/signup/signup_state.dart

Change the URL to http://risu.dns-dynamic.net
UT Front (Mobile): 69.7%
UT Back: 38.28%
Closes #216

Nginx implementation

---

Server/controllers/Web/user.js
Server/prisma/schema.prisma

close #289
No front end so no screen
No data added so no docs and no new unit since they already exists

[ADD] Link to organization during register

---

Configurateur/front/lib/components/recap_panel.dart
Configurateur/front/lib/screens/container-creation/payment_screen.dart
Configurateur/front/test/components/recap_panel_test.dart
Configurateur/front/test/container-creation/design_screen_test.dart
Configurateur/front/test/container-creation/payment_screen_test.dart
Server/fixtures/mobile.js

- Update fixtures
- Remove input fields in payment screen
- update the correct data for recap panel

[FIX] Missing informations on fixtures and bad display in recap panel

---

Application/mobile/app_code/lib/pages/rent/confirm/confirm_rent_page.dart
Application/mobile/app_code/lib/pages/rent/confirm/confirm_rent_state.dart
Application/mobile/app_code/lib/pages/rent/rent_state.dart
Application/mobile/app_code/lib/pages/rent/return_state.dart
Application/mobile/app_code/test/confirm_rent_test.dart
Server/routes/Mobile/rent.js

also fix redirection from my location to the linked article

[FIX] Mail send invoice from location confirmation

---

Application/mobile/app_code/lib/pages/article/favorite/favorite_page.dart
Application/mobile/app_code/lib/pages/article/favorite/favorite_state.dart
Application/mobile/app_code/lib/pages/opinion/opinion_page.dart
Application/mobile/app_code/lib/pages/opinion/opinion_state.dart
Application/mobile/app_code/test/favorite_test.dart
Application/mobile/app_code/test/opinion_test.dart

.Add News tests in the front mobile
pages: item opinions, favorites

Unit testing/mobile front/hugo

---

Application/mobile/app_code/lib/pages/article/details_state.dart

[ADD] translation + fix getSimilarArticles

---

Application/mobile/app_code/lib/l10n/app_en.arb
Application/mobile/app_code/lib/l10n/app_fr.arb
Application/mobile/app_code/lib/pages/contact/conversation_state.dart
Application/mobile/app_code/test/conversation_test.dart
Application/mobile/app_code/test/rent_return_test.dart
Application/mobile/app_code/test/rentals_test.dart
Configurateur/front/lib/components/tickets_page.dart
Configurateur/front/test/ticket_page_test.dart
Server/docs/paths/Mobile/contact/assignedInfo.js
Server/docs/paths/Web/tickets/assignedInfo.js
Server/docs/paths/index.js
Server/routes/Mobile/tickets.js
Server/routes/Web/tickets.js
Server/tests/web/tickets.test.js

Now you can know who you are talking to in the ticket
Before, you only got the date

[ALL] Tickets Contact Name

---

Configurateur/front/lib/app_routes.dart
Configurateur/front/lib/components/custom_header.dart
Configurateur/front/lib/components/dialog/save_dialog.dart
Configurateur/front/lib/screens/container-creation/container_creation/container_creation.dart
Configurateur/front/lib/screens/container-creation/design_screen/design_screen.dart
Configurateur/front/lib/screens/container-creation/payment_screen/payment_screen.dart
Configurateur/front/lib/screens/container-creation/recap_screen/recap_screen.dart
Configurateur/front/lib/screens/container-creation/shape_screen/shape_screen.dart
Configurateur/front/lib/screens/landing-page/landing_page.dart
Configurateur/front/lib/screens/save_container/my_container.dart
Configurateur/front/test/container-creation/design_screen_test.dart
Configurateur/front/test/container-creation/recap_screen_test.dart

- Handle refresh event during the whole container creation proccess
[Capture vidéo du 2024-06-23 17-24-39.webm](https://github.com/H-chauvet/RISU/assets/64684672/ecf1cc4d-4a58-4b24-a7c1-e3802df1d982)

Refresh handling in container creation

---

Application/mobile/app_code/lib/l10n/app_en.arb
Application/mobile/app_code/lib/l10n/app_fr.arb
Application/mobile/app_code/lib/pages/article/details_state.dart
Application/mobile/app_code/test/article_details_test.dart

- Move the user opinions on the article's details page
- Change the "Similar articles" title's format
[Screen_recording_20240710_163622.webm](https://github.com/H-chauvet/RISU/assets/72006230/801f212f-e3d5-4f47-ab1d-8b7707c19dfc)

377 mobile move articles feedbacks in the articles details

---

Configurateur/front/lib/components/custom_header.dart
Configurateur/front/lib/components/custom_toast.dart
Configurateur/front/lib/components/dialog/rating_dialog_content/rating_dialog_content.dart
Configurateur/front/lib/components/google/google.dart
Configurateur/front/lib/components/items-information.dart
Configurateur/front/lib/components/tickets_page.dart
Configurateur/front/lib/network/informations.dart
Configurateur/front/lib/screens/company-profil/company-profil.dart
Configurateur/front/lib/screens/company-profil/container-profil.dart
Configurateur/front/lib/screens/company/company.dart
Configurateur/front/lib/screens/container-creation/container_creation/container_creation.dart
Configurateur/front/lib/screens/container-creation/design_screen/design_screen.dart
Configurateur/front/lib/screens/container-creation/maps_screen/maps_screen.dart
Configurateur/front/lib/screens/container-creation/payment_screen/payment_screen.dart
Configurateur/front/lib/screens/container-list/container_list.dart
Configurateur/front/lib/screens/feedbacks/feedbacks.dart
Configurateur/front/lib/screens/login/login.dart
Configurateur/front/lib/screens/password-recuperation/password_change.dart
Configurateur/front/lib/screens/password-recuperation/password_recuperation.dart
Configurateur/front/lib/screens/profile/profile_page.dart
Configurateur/front/lib/screens/recap-config/recap_config.dart
Configurateur/front/lib/screens/register-confirmation/register_confirmation.dart
Configurateur/front/lib/screens/user-list/user_list.dart
Configurateur/front/test/company_profil_test.dart
Configurateur/front/test/ticket_page_test.dart
Configurateur/front/test/user_test.dart

Custom toast is displayed in every pages
The toast has a title "Success" or "Error" based on the context
Green and red color based on the artistic direction are used for the custom toast
Icon "Check" or Icon "Cross" is used depending if it's a success or an error
Progress bar showing the remaining time before the toast disappears

[ADD] Custom toast, for the everything on the WEB

---

Configurateur/front/lib/components/dialog/delete_container_dialog.dart
Configurateur/front/lib/screens/container-creation/container_creation/container_creation.dart
Configurateur/front/lib/screens/container-creation/design_screen/design_screen.dart
Configurateur/front/lib/screens/container-creation/recap_screen/recap_screen.dart
Configurateur/front/lib/screens/container-creation/shape_screen/shape_screen.dart
Configurateur/front/lib/services/locker_service.dart
Configurateur/front/test/container-creation/container_creation_test.dart
Configurateur/front/test/container-creation/design_screen_test.dart
Configurateur/front/test/container-creation/shape_screen_test.dart

- Fix bug of delete lockers. Before we can remove the top of a locker with the bottom of another locker. The first exemple of the video would have work without the fix
[Capture vidéo du 2024-07-22 15-41-50.webm](https://github.com/user-attachments/assets/cd15d23d-eebd-4bac-958a-6da0198bb940)

375 web bug delete lockers

---

Application/mobile/app_code/lib/components/alert_dialog.dart
Application/mobile/app_code/lib/l10n/app_en.arb
Application/mobile/app_code/lib/l10n/app_fr.arb
Application/mobile/app_code/lib/pages/article/details_state.dart
Application/mobile/app_code/lib/pages/article/favorite/favorite_state.dart
Application/mobile/app_code/lib/pages/article/list_state.dart
Application/mobile/app_code/lib/pages/contact/contact_state.dart
Application/mobile/app_code/lib/pages/contact/conversation_state.dart
Application/mobile/app_code/lib/pages/contact/new_ticket_state.dart
Application/mobile/app_code/lib/pages/container/container_state.dart
Application/mobile/app_code/lib/pages/login/ask_reset_password/ask_reset_password_state.dart
Application/mobile/app_code/lib/pages/login/login_state.dart
Application/mobile/app_code/lib/pages/map/map_state.dart
Application/mobile/app_code/lib/pages/opinion/opinion_state.dart
Application/mobile/app_code/lib/pages/profile/informations/informations_state.dart
Application/mobile/app_code/lib/pages/rent/confirm/confirm_rent_state.dart
Application/mobile/app_code/lib/pages/rent/rent_state.dart
Application/mobile/app_code/lib/pages/rent/rental_state.dart
Application/mobile/app_code/lib/pages/rent/return_state.dart
Application/mobile/app_code/lib/pages/reset_password/reset_password_state.dart
Application/mobile/app_code/lib/pages/settings/settings_pages/notifications/notifications_state.dart
Application/mobile/app_code/lib/pages/settings/settings_state.dart
Application/mobile/app_code/lib/pages/signup/signup_state.dart
Application/mobile/app_code/lib/utils/check_signin.dart

- Add an AlertDialog
- Show that AlertDialog whenever the server replies with a status code of 401
- Redirects to the LoginPage when closing that AlertDialog
[Screen_recording_20240724_152848.webm](https://github.com/user-attachments/assets/c589ef5f-11e0-47b0-947b-aa1626522c36)

378 mobile handle token expiration

---

Configurateur/front/lib/screens/company-creation/company-creation.dart
Server/controllers/Common/container.js
Server/routes/Web/container.js

- Boolean not initialized correctly

[FIX] Manager boolean value when creating company

---

Application/mobile/app_code/lib/l10n/app_en.arb
Application/mobile/app_code/lib/l10n/app_fr.arb
Application/mobile/app_code/lib/pages/article/details_state.dart
Application/mobile/app_code/lib/pages/article/list_state.dart
Application/mobile/app_code/lib/utils/share_deeplink.dart

Two buttons in the mobile app are added:
One to share container (article list)
Another one to share article (details of it)
Both links are copied to the clipboard

[MOBILE] Button to share containers & articles

---

Configurateur/front/lib/components/tickets_page.dart
Configurateur/front/lib/screens/admin/admin.dart
Configurateur/front/lib/screens/company-creation/company-creation.dart
Configurateur/front/lib/screens/company-profil/company-profil.dart
Configurateur/front/lib/screens/company-profil/container-profil.dart
Configurateur/front/lib/screens/company-profil/object-creation.dart
Configurateur/front/lib/screens/company/company.dart
Configurateur/front/lib/screens/confidentiality/confidentiality.dart
Configurateur/front/lib/screens/container-creation/confirmation_screen/confirmation_screen.dart
Configurateur/front/lib/screens/container-creation/container_creation/container_creation.dart
Configurateur/front/lib/screens/container-creation/design_screen/design_screen.dart
Configurateur/front/lib/screens/container-creation/maps_screen/maps_screen.dart
Configurateur/front/lib/screens/container-creation/payment_screen/payment_screen.dart
Configurateur/front/lib/screens/container-creation/recap_screen/recap_screen.dart
Configurateur/front/lib/screens/container-creation/shape_screen/shape_screen.dart
Configurateur/front/lib/screens/container-list/container_list.dart
Configurateur/front/lib/screens/faq/faq.dart
Configurateur/front/lib/screens/feedbacks/feedbacks.dart
Configurateur/front/lib/screens/landing-page/landing_page.dart
Configurateur/front/lib/screens/login/login.dart
Configurateur/front/lib/screens/not-found/not_found.dart
Configurateur/front/lib/screens/profile/profile_page.dart
Configurateur/front/lib/screens/register-confirmation/confirmed_user.dart
Configurateur/front/lib/screens/register/register.dart
Configurateur/front/lib/screens/user-list/user_list.dart
Configurateur/front/test/confidentiality_test.dart
Configurateur/front/test/confirmed_user_test.dart
Configurateur/front/test/container-creation/confirmation_screen_test.dart

Reduce space between footer and the end of the page

---

Server/controllers/Mobile/auth.js

Revert the register with a deeplink in the server
The deeplink are not working right know due to security hash issue

[FIX] Register with deeplink (Revert)

---

Application/mobile/app_code/lib/pages/login/login_state.dart
Application/mobile/app_code/lib/pages/settings/settings_pages/language/modal.dart
Application/mobile/app_code/lib/utils/user_data.dart
Configurateur/front/lib/components/custom_header.dart
Configurateur/front/lib/screens/login/login.dart
Server/controllers/Mobile/user.js
Server/controllers/Web/user.js
Server/routes/Web/user.js
Server/tests/web/user.test.js

Load user language preferences when logging in

[ADD] Change languages in the database 

---

Configurateur/front/lib/l10n/app_en.arb
Configurateur/front/lib/l10n/app_fr.arb
Configurateur/front/lib/screens/landing-page/landing_page.dart
Configurateur/front/test/landing_page_test.dart

[ADD] Landing page web for mobile

---

Application/mobile/app_code/android/app/build.gradle
Application/mobile/app_code/android/app/src/main/AndroidManifest.xml
Application/mobile/app_code/lib/utils/share_deeplink.dart
Server/controllers/Mobile/auth.js

[FIX] Deeplinks works

---

Application/mobile/app_code/lib/components/bottomnavbar.dart
Application/mobile/app_code/lib/pages/home/home_state.dart
Application/mobile/app_code/test/bottomnavbar_test.dart

Now the bottom nav bar always has 5 icons

[FIX] Bug with bottom nav bar index
